pipeline:
  test:
    image: golang
    commands:
      - cd posix
      - tar -xf fixtures.tar -C /
      - go test -v
  publish:
    image: plugins/docker
    repo: plugins/git
    tags: [ "next" ]
    secrets: [ docker_username, docker_password ]
    when:
      event: push