FROM 10.10.16.254:447/plugins/base:linux-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Git" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache --purge git openssh curl perl && rm -rf /var/cache/apk/* /tmp/*

ADD docker/drone-git /bin/
ENTRYPOINT ["/bin/drone-git"]
